filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log
# docker compose logs
# - type: container
#   paths:
#     - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"


output.logstash:
  hosts: ["logstash:5044"]
