{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-auth
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.auth.grpc.port }}
      targetPort: {{ .Values.auth.grpc.targetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
{{- end }}