{{- if .Values.kong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-kong
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: kong
spec:
  type: {{ .Values.kong.service.type }}
  ports:
    - port: {{ .Values.kong.service.port }}
      targetPort: {{ .Values.kong.service.targetPort }}
      protocol: TCP
      name: proxy
    - port: {{ .Values.kong.service.adminPort }}
      targetPort: {{ .Values.kong.service.adminTargetPort }}
      protocol: TCP
      name: admin
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kong
{{- end }}