{{- if .Values.kong.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservices.fullname" . }}-kong-config
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: kong
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: auth-service
        url: http://{{ include "microservices.fullname" . }}-auth:9001
        routes:
          - name: auth-routes
            paths:
              - /auth
            strip_path: true
            preserve_host: false
            protocols:
              - http
              - https
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE

      - name: post-service
        url: http://{{ include "microservices.fullname" . }}-post:9002
        routes:
          - name: post-routes
            paths:
              - /post
            strip_path: true
            preserve_host: false
            protocols:
              - http
              - https
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
{{- end }}