{{- if .Values.secrets.database.create }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.database.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if .Values.secrets.redis.create }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.redis.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if .Values.secrets.auth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.auth.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}