services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./kong/config.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"  # Main API Gateway port
      - "8443:8443"  # SSL port
      - "8001:8001"  # Admin API port
    depends_on:
      - auth-service
      - post-service
    networks:
      - backendworks
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: vector:24224  
        tag: kong-gateway

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=auth-service
    ports:
      - "9001:9001"
    env_file:
      - ./auth/.env.docker
    volumes:
      - ./auth:/app
      - /app/node_modules
    restart: on-failure
    networks:
      - backendworks
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: vector:24224  
        tag: auth-service

  post-service:
    build:
      context: ./post
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=post-service
    ports:
      - "9002:9002"
    env_file:
      - ./post/.env.docker
    volumes:
      - ./post:/app
      - /app/node_modules
    restart: on-failure
    networks:
      - backendworks
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: vector:24224 
        tag: post-service

networks:
  backendworks:
    external: true