version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-master123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-master123}
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-master123}
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "28017:28017"
    command: --replSet rs0
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
  rabbit_data:
  redis_data:
  mongo_data:
