version: "3.2"
services:
  user:
    image: hmake98/nestms-user:latest
    env_file:
      - ./user/.env
  post:
    image: hmake98/nestms-post:latest
    env_file:
      - ./post/.env
  notification:
    image: hmake98/nestms-notification:latest
    env_file:
      - ./notification/.env
  files:
    image: hmake98/nestms-files:latest
    env_file:
      - ./files/.env
  mailer:
    image: hmake98/nestms-mailer:latest
    env_file:
      - ./mailer/.env
  logger:
    image: hmake98/nestms-logger:latest
    env_file:
      - ./logger/.env
  token:
    image: hmake98/nestms-token:latest
    env_file:
      - ./token/.env
  kong:
    image: hmake98/kong:latest
    command: "kong start"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8080
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:9000
    ports:
      - 8080:8080
      - 9000:9000
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=master123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3-management"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
  cache:
    image: redis:latest
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: master123
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  fluent-bit:
    hostname: fluentd
    build:
      context: ./fluent-bit
      dockerfile: Dockerfile
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    ports:
      - "24224:24224"
      - "24224:24224/udp"
volumes:
  mongo_data:
    driver_opts:
      performance-mode: maxIO
      throughput-mode: bursting
      uid: 0
      gid: 0
  pg_data:
    driver_opts:
      performance-mode: maxIO
      throughput-mode: bursting
      uid: 0
      gid: 0
  rabbit_data:
    driver_opts:
      performance-mode: maxIO
      throughput-mode: bursting
      uid: 0
      gid: 0
