version: "3"

services:
  loki:
    image: grafana/loki:latest
    restart: on-failure
    container_name: loki
    expose:
      - "3100"
  grafana:
    image: grafana/grafana:latest
    restart: on-failure
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: on-failure
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
