version: "3"

services:
  user:
    image: 339146391262.dkr.ecr.ap-south-1.amazonaws.com/nestjs-ms:user
    env_file:
      - ./user/.env
  post:
    image: 339146391262.dkr.ecr.ap-south-1.amazonaws.com/nestjs-ms:post
    env_file:
      - ./post/.env
  notification:
    image: 339146391262.dkr.ecr.ap-south-1.amazonaws.com/nestjs-ms:notification
    env_file:
      - ./notification/.env
  files:
    image: 339146391262.dkr.ecr.ap-south-1.amazonaws.com/nestjs-ms:files
    env_file:
      - ./files/.env
  mailer:
    image: 339146391262.dkr.ecr.ap-south-1.amazonaws.com/nestjs-ms:mailer
    env_file:
      - ./mailer/.env
  token:
    image: 339146391262.dkr.ecr.ap-south-1.amazonaws.com/nestjs-ms:token
    env_file:
      - ./token/.env
