{{- $dot := . }}
{{- range $value := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $value.name }}"
  namespace: "{{ $value.nameSpace }}"
  labels:
    app: "{{ $value.name }}"
    chart: "{{ $dot.Chart.Name }}"
    version: "{{ $dot.Chart.Version }}"
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app: "{{ $value.name }}"
      chart: "{{ $dot.Chart.Name }}"
      version: "{{ $dot.Chart.Version }}"
  template:
    metadata:
      labels:
        app: "{{ $value.name }}"
        chart: "{{ $dot.Chart.Name }}"
        version: "{{ $dot.Chart.Version }}"
    spec:
      containers:
        - name: "{{ $value.name }}"
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $value.image.pullPolicy }}
          env:          
            {{- range $value.env }}
              - name: {{ .key }}
                value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ $value.service.internalPort }}
              protocol: TCP
      restartPolicy: {{ $value.deployment.restartPolicy }}
{{- end }}