{{- range $serviceName, $serviceConfig := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  namespace: {{ $serviceConfig.nameSpace }}
  labels:
    app: "{{ $serviceName }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  replicas: {{ $serviceConfig.replicaCount }}
  selector:
    matchLabels:
      app: "{{ $serviceName }}"
      release: "{{ $.Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ $serviceName }}"
        release: "{{ $.Release.Name }}"
      annotations:
        {{- range $key, $value := $serviceConfig.podAnnotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
    spec:
      containers:
        - name: {{ $serviceName }}
          image: "{{ $serviceConfig.image.repository }}:{{ $serviceConfig.image.tag }}"
          imagePullPolicy: {{ $serviceConfig.image.pullPolicy }}
          ports:
            - containerPort: {{ $serviceConfig.service.internalPort }}
          env:
            {{- range $key, $value := $serviceConfig.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml $serviceConfig.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
      restartPolicy: {{ $serviceConfig.deployment.restartPolicy }}
{{- end }}
