{{- if .Values.kong.ingressController.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Values.kong.name }}
    annotations:
      kubernetes.io/ingress.class: {{ .Values.kong.ingressController.ingressClass }}
      konghq.com/strip-path: 'true'
    labels:
      chart: "{{ .Chart.Name }}"
      version: "{{ .Chart.Version }}"
spec:
  rules:
  {{- range $value := .Values.kong.paths }}
  - http:
      paths:
      - path: {{ $value.path }}
        pathType: {{ $value.pathType }}
        backend:
          service: 
            name: {{ $value.name }}
            port: 
              number: {{ $value.port }}
  {{- end }}
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-limiting
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  minute: 5
  policy: local
plugin: rate-limiting
{{- end }}
