{{- if .Values.kong.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nestjs-gateway
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/component: server
        chart: "{{ .Chart.Name }}"
        version: "{{ .Chart.Version }}"
spec:
    ingressClassName: {{ .Values.kong.ingressController.ingressClass }}
    rules:
    {{- range $value := .Values.kong.paths }}
    - http:
        paths:
        - path: {{ $value.path }}
          pathType: {{ $value.pathType }}
          backend:
            service: 
              name: {{ $value.name }}
              port:
                number: {{ $value.port }}
    {{- end }}
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-limiting
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  minute: 5
  policy: local
plugin: rate-limiting
{{- end }}
