{{- range $serviceName, $serviceConfig := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
  namespace: {{ $serviceConfig.nameSpace }}
  labels:
    app: "{{ $serviceName }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- if $serviceConfig.env.ACCESS_TOKEN_SECRET_KEY }}
  ACCESS_TOKEN_SECRET_KEY: "{{ $serviceConfig.env.ACCESS_TOKEN_SECRET_KEY | b64enc }}"
  {{- end }}
  {{- if $serviceConfig.env.REFRESH_TOKEN_SECRET_KEY }}
  REFRESH_TOKEN_SECRET_KEY: "{{ $serviceConfig.env.REFRESH_TOKEN_SECRET_KEY | b64enc }}"
  {{- end }}
  {{- if $serviceConfig.env.AWS_S3_ACCESS_KEY }}
  AWS_S3_ACCESS_KEY: "{{ $serviceConfig.env.AWS_S3_ACCESS_KEY | b64enc }}"
  {{- end }}
  {{- if $serviceConfig.env.AWS_S3_SECRET_KEY }}
  AWS_S3_SECRET_KEY: "{{ $serviceConfig.env.AWS_S3_SECRET_KEY | b64enc }}"
  {{- end }}
  {{- if $serviceConfig.env.AWS_SES_ACCESS_KEY }}
  AWS_SES_ACCESS_KEY: "{{ $serviceConfig.env.AWS_SES_ACCESS_KEY | b64enc }}"
  {{- end }}
  {{- if $serviceConfig.env.AWS_SES_SECRET_KEY }}
  AWS_SES_SECRET_KEY: "{{ $serviceConfig.env.AWS_SES_SECRET_KEY | b64enc }}"
  {{- end }}
{{- end }}
