{{- range $serviceName, $serviceConfig := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  namespace: {{ $serviceConfig.nameSpace }}
  labels:
    app: {{ $serviceName }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    {{- if $serviceConfig.service.annotations }}
    annotations:
      {{- range $key, $value := $serviceConfig.service.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
spec:
  type: {{ $serviceConfig.service.type }}
  ports:
    - port: {{ $serviceConfig.service.externalPort }}
      targetPort: {{ $serviceConfig.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $serviceName }}
    release: {{ $.Release.Name }}
{{- end }}
