[sources.fluentd_source]
type = "fluent"
address = "0.0.0.0:24224"

# Output to Loki
[sinks.loki]
type = "loki"
inputs = ["fluentd_source"]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.service = "{{ container_name }}"