_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://auth-service:9001
    routes:
      - name: auth-routes
        paths:
          - /auth
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE

  - name: post-service
    url: http://post-service:9002
    routes:
      - name: post-routes
        paths:
          - /post
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
