# Default values for nestjs-microservices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
name: auth
nameSpace: default
image:
  repository: nestjs-microservices_auth
  tag: latest
  pullPolicy: Never
deployment:
  restartPolicy: Always
env:
  - key: NODE_ENV
    value: development
  - key: PORT
    value: "9001"
  - key: TOKEN_EXP
    value: 86400s
  - key: AUTH_SECRET
    value: my_secret_key
  - key: RABBITMQ_URL
    value: amqp://admin:master123@host.minikube.internal:5672
  - key: RABBITMQ_TOKEN_QUEUE
    value: token_queue
  - key: RABBITMQ_MAILER_QUEUE
    value: mailer_queue
  - key: RABBITMQ_FILES_QUEUE
    value: files_queue
  - key: RABBITMQ_AUTH_QUEUE
    value: auth_queue
  - key: RABBITMQ_NOTIFICATION_QUEUE
    value: notification_queue
  - key: DATABASE_URL
    value: "postgresql://admin:master123@host.minikube.internal:5432/user-db?schema=public"
service:
  name: auth
  type: NodePort
  externalPort: 80
  internalPort: 9001
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi